exports.paginaListaCompositores = function(listaComp, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1>Compositores</h1>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos Musicais</b></a>
                </header>
            <div class="w3-container">
            <div class="w3-cell-row">
                <div class="w3-cell">
                    <h2><b>Lista de Compositores</b></h2> 
                </div>
                <div class="w3-cell">
                    <p><a href="/registo/compositores" class="w3-button w3-round w3-grey"><b>Adicionar Compositor</b></a></p>
                </div>
                <table class="w3-table-all">
                    <tr>
                        <th>Nome</th>
                        <th>Data Nascimento</th>
                        <th>Período</th>
                        <th>Ações</th>
                    </tr>`
    
    listaComp.forEach(element => {
        pagHTML += `<tr>
                    <td><a href="/compositores/${element.id}">${element.nome}</a></td>
                    <td>${element.dataNasc}</td>
                    <td><a href="/periodos/${element.periodo}">${element.periodo}</a></td>
                    <td>
                        [<a href="/edit/compositores/${element.id}">Editar</a>]
                        [<a href="/delete/compositores/${element.id}">Apagar</a>]
                    </td>
                 </tr>
        `
    });
        
        pagHTML += `
            </table>
                </div>
                    <footer class="w3-container w3-blue">
                        <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                    </footer>
                </div>
            </body>
        </html>
        `

        return pagHTML
}

exports.paginaCompositor = function(compositor, d)
{
    var html = `
    <html>
        <head>
            <meta charset="utf-8" />
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor: ${compositor.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>${compositor.nome}</b></h2>
                <div class="w3-container w3-margin-bottom">
                    <ul class="w3-ul w3-card-4">
                        <li><b>Biografia:</b> <p>${compositor.bio}</p></li>
                        <li><b>Data de Nascimento:</b> ${compositor.dataNasc}</li>
                        <li><b>Data de Obito:</b> ${compositor.dataObito}</li>
                        <li><b>Período:</b> <a href="/periodos/${compositor.periodo}">${compositor.periodo} </a></li>
                    </ul>
                </div>
                <div class="w3-cell w3-container">
                    <a href="/compositores" class="w3-button w3-teal"><b>Voltar à lista de Compositores</b></a>
                    <a href="/edit/compositores/${compositor.id}" class="w3-button w3-blue"><b>Editar</b></a>
                    <a href="/delete/compositores/${compositor.id}" class="w3-button w3-red"><b>Apagar</b></a>
                </div>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return html
}

exports.paginaEditCompositor = function(compositor, d)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Edit do Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Ir para a lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Edit do Compositor</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Id</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="id" readonly value="${compositor.id}"/>
                        <label><b>Nome*</b></label>
                        <input class="w3-input  w3-border w3-round" type="text" name="nome" required value="${compositor.nome}"/>
                        <label><b>Data Nascimento</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="dataNasc" value="${compositor.dataNasc}"/>
                        <label><b>Data de Obíto</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="dataObito" value="${compositor.dataObito}"/>
                        <label><b>Biografia</b></label>
                        <textarea class="w3-input w3-border w3-round" name="bio"/>${compositor.bio}</textarea>
                        <label><b>Período</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="periodo" value="${compositor.periodo}" readonly/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Guardar Alterações</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.paginaRegistoCompositores = function(periodos, d)
{
    html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registro de Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Ir para a lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
                </header>
                <div class="w3-container">
                <h2 class="w3-center"><b>Registo de um compositor</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Id</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="id" required/>
                        <label><b>Nome</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="nome" required/>
                        <label><b>Data Nascimento</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="dataNasc"/>
                        <label><b>Data de Obíto</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="dataObito"/>
                        <label><b>Biografia</b></label>
                        <textarea class="w3-input w3-border w3-round" name="bio"/></textarea>
                        <label><b>Período</b></label>`
                    
                    periodos.forEach(periodo => {
                        html += `<br><input class="w3-radio w3-border" id="${periodo.id}" type="radio" name="periodo" value=${periodo.designacao} required/>`
                        html += `<label for="${periodo.id}">${periodo.designacao}</label><br>`
                    })
                    html += `<fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Registar Compositor</button>
                </form>
                </div>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return html
}


exports.paginaListaPeriodos = function(listaPeriodos, d) {
    var html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Períodos</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                </header>
            <div class="w3-container">
            <div class="w3-cell-row" style="width:30%">
                <div class="w3-cell">
                    <h2><b>Lista de Períodos</b></h2> 
                </div>
                <div class="w3-cell">
                    <p><a href="/registo/periodos" class="w3-button w3-round w3-grey"><b>Adicionar Período</b></a></p>
                </div>
            </div>
                <table class="w3-table-all">
                    <tr>
                        <th>Designação</th>
                        <th>Ações</th>
                    </tr>`

    listaPeriodos.forEach(element => {
        html += `<tr>
                    <td><a href="/periodos/${element.designacao}">${element.designacao}</a></td>
                    <td>
                        [<a href="/edit/periodos/${element.id}">Editar</a>]
                        [<a href="/delete/periodos/${element.id}">Apagar</a>]
                    </td>
                 </tr>`
    });         

            html += `
                </table>                    
            </div>
            <footer class="w3-container w3-teal w3-center">
            <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
            </footer>
            </div>
           
        </body>
    </html>
    `
    return html
}

exports.paginaPeriodo = function(periodo, d)
{
    var html = `
    <html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="w3.css"/>
        <title>Periodo</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-center w3-teal">
                <h1><b>Compositores Musicais</b></h1>
                <a href="/compositores" class="w3-button"><b>Ir para a lista de Compositores</b></a>
                <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
            </header>
            <h2 class="w3-center"><b>Período ID: ${periodo[0].id}</b></h2>
            <h2 class="w3-center"><b>Designação: ${periodo[0].designacao}</b></h2>
            <div class="w3-cell w3-container">
                <a href="/periodos" class="w3-button w3-teal"><b>Voltar à lista de Períodos</b></a>
                <a href="/edit/periodos/${periodo[0].id}" class="w3-button w3-blue"><b>Editar Período</b></a>
                <a href="/delete/periodos/${periodo[0].id}" class="w3-button w3-red"><b>Apagar Período</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center w3-margin-top">
                <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
            </footer>
        </div>
    </body>
    </html>
    `
    return html
}

exports.paginaEditPeriodo = function(periodo, d)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Edit do Período</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Ir para a lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Edit do Período</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>ID</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="id" required value=${periodo.id} readonly/>
                        <label><b>Designação</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="designacao" required value="${periodo.designacao}"/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Guardar Alterações</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}


exports.paginaRegistoPeriodo = function(d)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registro de Periodo</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Ir para a lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Ir para a lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Registo de um Periodo</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                    <label><b>Designação</b></label>
                    <input class="w3-input w3-border w3-round" type="text" name="designacao" required/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Registar Periodo</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h5>Generated by Lucas Oliveira Powered by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
}